name: gyver_hub
description: Панель управления для esp8266, esp32 и других Arduino. Конструктор интерфейса, интеграция в умный дом

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0-beta.25
  path_provider: ^2.1.1
  mini_server: ^1.1.0
  url_launcher: ^6.1.14
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  lottie: ^2.7.0
  permission_handler: ^11.0.1
  open_file: ^3.3.2


#  flutter_downloader: ^1.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/app_icon_foreground.png"
  image_path_ios: "assets/icons/app_icon.png"
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/animations/